import 'package:flutter/material.dart';

import '../../constants/colors.dart';
import '../../constants/fonts.dart';
import '../../constants/sizes.dart';

class MyTextTheme {
  MyTextTheme._();

  static TextTheme get lightTextTheme => TextTheme(
        displayLarge: TextStyle(
          fontSize: Sizes.fontSizeDisplayLg,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: -0.5,
          height: 1.1,
        ),
        displayMedium: TextStyle(
          fontSize: Sizes.fontSizeDisplayMd,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: -0.25,
          height: 1.15,
        ),
        displaySmall: TextStyle(
          fontSize: Sizes.fontSizeDisplaySm,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          height: 1.2,
        ),
        headlineLarge: TextStyle(
          fontSize: Sizes.fontSizeDisplayXs,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          height: 1.2,
        ),
        headlineMedium: TextStyle(
          fontSize: Sizes.fontSizeXxxl,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          height: 1.25,
        ),
        headlineSmall: TextStyle(
          fontSize: Sizes.fontSizeXxl,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.1,
          height: 1.3,
        ),
        titleLarge: TextStyle(
          fontSize: Sizes.fontSizeXl,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.15,
          height: 1.3,
        ),
        titleMedium: TextStyle(
          fontSize: Sizes.fontSizeLg,
          fontWeight: FontWeight.w500,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.1,
          height: 1.35,
        ),
        titleSmall: TextStyle(
          fontSize: Sizes.fontSizeMd,
          fontWeight: FontWeight.w500,
          color: MyColors.textSecondary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.1,
          height: 1.4,
        ),
        bodyLarge: TextStyle(
          fontSize: Sizes.fontSizeMd,
          fontWeight: FontWeight.normal,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.5,
          height: 1.5,
        ),
        bodyMedium: TextStyle(
          fontSize: Sizes.fontSizeSm,
          fontWeight: FontWeight.normal,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.25,
          height: 1.5,
        ),
        bodySmall: TextStyle(
          fontSize: Sizes.fontSizeXs,
          fontWeight: FontWeight.normal,
          color: MyColors.textSecondary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.4,
          height: 1.4,
        ),
        labelLarge: TextStyle(
          fontSize: Sizes.fontSizeSm,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.75,
          height: 1.2,
        ),
        labelMedium: TextStyle(
          fontSize: Sizes.fontSizeXs,
          fontWeight: FontWeight.w500,
          color: MyColors.textSecondary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.5,
          height: 1.3,
        ),
        labelSmall: TextStyle(
          fontSize: Sizes.fontSizeXxs,
          fontWeight: FontWeight.w500,
          color: MyColors.textSecondary,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 1.0,
          height: 1.2,
        ),
      );

  static TextTheme get darkTextTheme => TextTheme(
        displayLarge: TextStyle(
          fontSize: Sizes.fontSizeDisplayLg,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: -0.5,
          height: 1.1,
        ),
        displayMedium: TextStyle(
          fontSize: Sizes.fontSizeDisplayMd,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: -0.25,
          height: 1.15,
        ),
        displaySmall: TextStyle(
          fontSize: Sizes.fontSizeDisplaySm,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          height: 1.2,
        ),
        headlineLarge: TextStyle(
          fontSize: Sizes.fontSizeDisplayXs,
          fontWeight: FontWeight.bold,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          height: 1.2,
        ),
        headlineMedium: TextStyle(
          fontSize: Sizes.fontSizeXxxl,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          height: 1.25,
        ),
        headlineSmall: TextStyle(
          fontSize: Sizes.fontSizeXxl,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.1,
          height: 1.3,
        ),
        titleLarge: TextStyle(
          fontSize: Sizes.fontSizeXl,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.15,
          height: 1.3,
        ),
        titleMedium: TextStyle(
          fontSize: Sizes.fontSizeLg,
          fontWeight: FontWeight.w500,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.1,
          height: 1.35,
        ),
        titleSmall: TextStyle(
          fontSize: Sizes.fontSizeMd,
          fontWeight: FontWeight.w500,
          color: MyColors.textSecondaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.1,
          height: 1.4,
        ),
        bodyLarge: TextStyle(
          fontSize: Sizes.fontSizeMd,
          fontWeight: FontWeight.normal,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.5,
          height: 1.5,
        ),
        bodyMedium: TextStyle(
          fontSize: Sizes.fontSizeSm,
          fontWeight: FontWeight.normal,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.25,
          height: 1.5,
        ),
        bodySmall: TextStyle(
          fontSize: Sizes.fontSizeXs,
          fontWeight: FontWeight.normal,
          color: MyColors.textSecondaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.4,
          height: 1.4,
        ),
        labelLarge: TextStyle(
          fontSize: Sizes.fontSizeSm,
          fontWeight: FontWeight.w600,
          color: MyColors.textPrimaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.75,
          height: 1.2,
        ),
        labelMedium: TextStyle(
          fontSize: Sizes.fontSizeXs,
          fontWeight: FontWeight.w500,
          color: MyColors.textSecondaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 0.5,
          height: 1.3,
        ),
        labelSmall: TextStyle(
          fontSize: Sizes.fontSizeXxs,
          fontWeight: FontWeight.w500,
          color: MyColors.textSecondaryDark,
          fontFamily: MyFonts.getFontFamily(),
          letterSpacing: 1.0,
          height: 1.2,
        ),
      );
}
