import 'package:flutter/material.dart';

import '../constants/colors.dart';
import '../constants/fonts.dart';
import 'widget_themes/index.dart';

class AppTheme {
  AppTheme._();

  static ThemeData get lightTheme => ThemeData(
        useMaterial3: true,
        fontFamily: MyFonts.getFontFamily(),
        brightness: Brightness.light,
        primaryColor: MyColors.primary,
        scaffoldBackgroundColor: MyColors.background,
        disabledColor: MyColors.textDisabled,
        colorScheme: ColorScheme.fromSeed(
          seedColor: MyColors.primary,
          brightness: Brightness.light,
          primary: MyColors.primary,
          onPrimary: MyColors.textOnPrimary,
          primaryContainer: MyColors.primary.withValues(alpha: 0.1),
          onPrimaryContainer: MyColors.primary,
          secondary: MyColors.secondary,
          onSecondary: MyColors.textOnPrimary,
          secondaryContainer: MyColors.secondary.withValues(alpha: 0.1),
          onSecondaryContainer: MyColors.secondary,
          tertiary: MyColors.accent,
          onTertiary: MyColors.textOnAccent,
          tertiaryContainer: MyColors.accent.withValues(alpha: 0.1),
          onTertiaryContainer: MyColors.accent,
          error: MyColors.error,
          onError: MyColors.textOnPrimary,
          errorContainer: MyColors.error.withValues(alpha: 0.1),
          onErrorContainer: MyColors.error,
          surface: MyColors.surface,
          onSurface: MyColors.textPrimary,
          surfaceContainerHighest: MyColors.container,
          onSurfaceVariant: MyColors.textSecondary,
          outline: MyColors.border,
          outlineVariant: MyColors.divider,
        ),
        textTheme: MyTextTheme.lightTextTheme,
        appBarTheme: MyAppBarTheme.lightAppBarTheme,
        elevatedButtonTheme: MyElevatedButtonTheme.lightElevatedButtonTheme,
        outlinedButtonTheme: MyOutlinedButtonTheme.lightOutlinedButtonTheme,
        inputDecorationTheme: MyTextFormFieldTheme.lightInputDecorationTheme,
        checkboxTheme: MyCheckboxTheme.lightCheckboxTheme,
        bottomSheetTheme: MyBottomSheetTheme.lightBottomSheetTheme,
        chipTheme: MyChipTheme.lightChipTheme,
      );

  static ThemeData get darkTheme => ThemeData(
        useMaterial3: true,
        fontFamily: MyFonts.getFontFamily(),
        brightness: Brightness.dark,
        primaryColor: MyColors.primaryDark,
        scaffoldBackgroundColor: MyColors.backgroundDark,
        disabledColor: MyColors.textDisabledDark,
        colorScheme: ColorScheme.fromSeed(
          seedColor: MyColors.primaryDark,
          brightness: Brightness.dark,
          primary: MyColors.primaryDark,
          onPrimary: MyColors.textOnPrimaryDark,
          primaryContainer: MyColors.primaryDark.withValues(alpha: 0.1),
          onPrimaryContainer: MyColors.primaryDark,
          secondary: MyColors.secondaryDark,
          onSecondary: MyColors.textOnPrimaryDark,
          secondaryContainer: MyColors.secondaryDark.withValues(alpha: 0.1),
          onSecondaryContainer: MyColors.secondaryDark,
          tertiary: MyColors.accentDark,
          onTertiary: MyColors.textOnAccentDark,
          tertiaryContainer: MyColors.accentDark.withValues(alpha: 0.1),
          onTertiaryContainer: MyColors.accentDark,
          error: MyColors.errorDark,
          onError: MyColors.textOnPrimaryDark,
          errorContainer: MyColors.errorDark.withValues(alpha: 0.1),
          onErrorContainer: MyColors.errorDark,
          surface: MyColors.surfaceDark,
          onSurface: MyColors.textPrimaryDark,
          surfaceContainerHighest: MyColors.containerDark,
          onSurfaceVariant: MyColors.textSecondaryDark,
          outline: MyColors.borderDark,
          outlineVariant: MyColors.dividerDark,
        ),
        textTheme: MyTextTheme.darkTextTheme,
        appBarTheme: MyAppBarTheme.darkAppBarTheme,
        elevatedButtonTheme: MyElevatedButtonTheme.darkElevatedButtonTheme,
        outlinedButtonTheme: MyOutlinedButtonTheme.darkOutlinedButtonTheme,
        inputDecorationTheme: MyTextFormFieldTheme.darkInputDecorationTheme,
        checkboxTheme: MyCheckboxTheme.darkCheckboxTheme,
        bottomSheetTheme: MyBottomSheetTheme.darkBottomSheetTheme,
        chipTheme: MyChipTheme.darkChipTheme,
      );
}
